import HeadingTitle from "@/components/HeadingTitle";
import Image from "next/image";

const WhyCpo = () => {
  return (
    <div className="xl:pt-[80px] lg:pt-[60px] pt-[40px]">
      <HeadingTitle title="Why Conventional Optics Fall Short in CPO" />

      <div className="xl:mt-12 lg:mt-10 mt-6 flex flex-col gap-10">
        {/* Texts */}
        <div className="flex flex-col gap-6">
          <h3 className="futura-bold text-[18px] lg:text-[19px] xl:text-[20px] text-black">
            Built Different. Designed for What's Next.
          </h3>
          <div className="flex flex-col gap-4">
            <p className="futura-medium text-[16px] lg:text-[17px] xl:text-[18px] text-[#676767]">
              Traditional micro-optics rely on curved, three-dimensional lens
              geometries, physically thick components that were designed for an
              era when space constraints were less demanding. In the tight
              confines of a CPO package, their bulky form factor limits
              integration density, makes precise alignment harder to maintain at
              scale, and leaves them vulnerable to thermal deformation under the
              heat generated by high-power chips.
            </p>
            <p className="futura-medium text-[16px] lg:text-[17px] xl:text-[18px] text-[#676767]">
              The difference is visible. Where traditional micro-optics produce
              a wide, diffuse beam with poor focus consistency, MetaOptics
              metalens delivers a tightly concentrated, high-precision beam
              profile.
            </p>
          </div>
        </div>

        {/* Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-10">
          {/* Traditional Card */}
          <div className="p-4 md:p-6 w-full flex-grow flex items-center justify-center">
            <Image
              src="/product-details/cpo/why-1.png"
              alt="Traditional Microlens"
              width={0}
              height={0}
              sizes="100vw"
              className="w-full h-auto object-contain"
              unoptimized
            />
          </div>

          {/* Metalens Card */}
          <div className="p-4 md:p-6 w-full flex-grow flex items-center justify-center">
            <Image
              src="/product-details/cpo/why-2.png"
              alt="Metaoptics Metalens"
              width={0}
              height={0}
              sizes="100vw"
              className="w-full h-auto object-contain"
              unoptimized
            />
          </div>
        </div>

        {/* Comparison Table - Desktop */}
        <div className="hidden md:block overflow-x-auto mt-6">
          <table className="w-full min-w-[700px] border-collapse border border-[#e3e3e3] text-center">
            <thead>
              <tr className="bg-[#EAEAEA]">
                <th className="border border-[#D3D0D0] py-4 px-4 futura-bold text-[#333] text-[15px] lg:text-[15.5px] xl:text-[16px] uppercase">
                  Feature
                </th>
                <th className="border border-[#D3D0D0] py-4 px-4 futura-medium text-[#676767] text-[15px] lg:text-[15.5px] xl:text-[16px] uppercase">
                  Traditional Micro-optics
                </th>
                <th className="border border-[#D3D0D0] py-4 px-4 futura-medium text-[#d34c39] text-[15px] lg:text-[15.5px] xl:text-[16px] uppercase">
                  Metaoptics Metalens
                </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="border border-[#D3D0D0] py-4 px-4 futura-bold text-[#333] text-[15px] lg:text-[15.5px] xl:text-[16px]">
                  Form Factor
                </td>
                <td className="border border-[#D3D0D0] py-4 px-4 futura-medium text-[#676767] text-[15px] lg:text-[15.5px] xl:text-[16px]">
                  Thick, Curved, 3D Geometry
                </td>
                <td className="border border-[#D3D0D0] py-4 px-4 futura-medium text-[#d34c39] text-[15px] lg:text-[15.5px] xl:text-[16px]">
                  Ultra-Thin, Planar, Flat Profile
                </td>
              </tr>
              <tr>
                <td className="border border-[#D3D0D0] py-4 px-4 futura-bold text-[#333] text-[15px] lg:text-[15.5px] xl:text-[16px]">
                  Beam Quality
                </td>
                <td className="border border-[#D3D0D0] py-4 px-4 futura-medium text-[#676767] text-[15px] lg:text-[15.5px] xl:text-[16px]">
                  Wide, Diffuse Beam
                </td>
                <td className="border border-[#D3D0D0] py-4 px-4 futura-medium text-[#d34c39] text-[15px] lg:text-[15.5px] xl:text-[16px]">
                  Tightly Focused, Precision Beam
                </td>
              </tr>
              <tr>
                <td className="border border-[#D3D0D0] py-4 px-4 futura-bold text-[#333] text-[15px] lg:text-[15.5px] xl:text-[16px]">
                  Alignment
                </td>
                <td className="border border-[#D3D0D0] py-4 px-4 futura-medium text-[#676767] text-[15px] lg:text-[15.5px] xl:text-[16px]">
                  Requires Active Mechanical Adjustment
                </td>
                <td className="border border-[#D3D0D0] py-4 px-4 futura-medium text-[#d34c39] text-[15px] lg:text-[15.5px] xl:text-[16px]">
                  Enables Passive Alignment
                </td>
              </tr>
              <tr>
                <td className="border border-[#D3D0D0] py-4 px-4 futura-bold text-[#333] text-[15px] lg:text-[15.5px] xl:text-[16px]">
                  Packaging Fit
                </td>
                <td className="border border-[#D3D0D0] py-4 px-4 futura-medium text-[#676767] text-[15px] lg:text-[15.5px] xl:text-[16px]">
                  Bulky, Limits Integration Density
                </td>
                <td className="border border-[#D3D0D0] py-4 px-4 futura-medium text-[#d34c39] text-[15px] lg:text-[15.5px] xl:text-[16px]">
                  Compact, Ideal For High-Density CPO
                </td>
              </tr>
              <tr>
                <td className="border border-[#D3D0D0] py-4 px-4 futura-bold text-[#333] text-[15px] lg:text-[15.5px] xl:text-[16px]">
                  Thermal Resilience
                </td>
                <td className="border border-[#D3D0D0] py-4 px-4 futura-medium text-[#676767] text-[15px] lg:text-[15.5px] xl:text-[16px]">
                  Vulnerable To Deformation Under Heat
                </td>
                <td className="border border-[#D3D0D0] py-4 px-4 futura-medium text-[#d34c39] text-[15px] lg:text-[15.5px] xl:text-[16px]">
                  Solid-State, Thermally Stable
                </td>
              </tr>
              <tr>
                <td className="border border-[#D3D0D0] py-4 px-4 futura-bold text-[#333] text-[15px] lg:text-[15.5px] xl:text-[16px]">
                  Manufacturing
                </td>
                <td className="border border-[#D3D0D0] py-4 px-4 futura-medium text-[#676767] text-[15px] lg:text-[15.5px] xl:text-[16px]">
                  Custom Fabrication, Complex Assembly
                </td>
                <td className="border border-[#D3D0D0] py-4 px-4 futura-medium text-[#d34c39] text-[15px] lg:text-[15.5px] xl:text-[16px]">
                  Wafer-Level, Semiconductor-Compatible
                </td>
              </tr>
              <tr>
                <td className="border border-[#D3D0D0] py-4 px-4 futura-bold text-[#333] text-[15px] lg:text-[15.5px] xl:text-[16px]">
                  Scalability
                </td>
                <td className="border border-[#D3D0D0] py-4 px-4 futura-medium text-[#676767] text-[15px] lg:text-[15.5px] xl:text-[16px]">
                  Difficult To Scale For High-Volume
                </td>
                <td className="border border-[#D3D0D0] py-4 px-4 futura-medium text-[#d34c39] text-[15px] lg:text-[15.5px] xl:text-[16px]">
                  Designed For High-Throughput Production
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        {/* Comparison Table - Mobile */}
        <div className="md:hidden mt-6 flex flex-col border border-[#D3D0D0] text-center w-full">
          {/* FEATURE Section */}
          <div className="bg-[#EAEAEA] py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-bold text-[#333] text-[14px] uppercase">
              Feature
            </span>
          </div>
          <div className="py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-bold text-[#333] text-[14px]">
              Form Factor
            </span>
          </div>
          <div className="py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-bold text-[#333] text-[14px]">
              Beam Quality
            </span>
          </div>
          <div className="py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-bold text-[#333] text-[14px]">
              Alignment
            </span>
          </div>
          <div className="py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-bold text-[#333] text-[14px]">
              Packaging Fit
            </span>
          </div>
          <div className="py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-bold text-[#333] text-[14px]">
              Thermal Resilience
            </span>
          </div>
          <div className="py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-bold text-[#333] text-[14px]">
              Manufacturing
            </span>
          </div>
          <div className="py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-bold text-[#333] text-[14px]">
              Scalability
            </span>
          </div>

          {/* METAOPTICS METALENS Section */}
          <div className="bg-[#EAEAEA] py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-medium text-[#d34c39] text-[14px] uppercase">
              Metaoptics Metalens
            </span>
          </div>
          <div className="py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-medium text-[#d34c39] text-[14px]">
              Ultra-Thin, Planar, Flat Profile
            </span>
          </div>
          <div className="py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-medium text-[#d34c39] text-[14px]">
              Tightly Focused, Precision Beam
            </span>
          </div>
          <div className="py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-medium text-[#d34c39] text-[14px]">
              Enables Passive Alignment
            </span>
          </div>
          <div className="py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-medium text-[#d34c39] text-[14px]">
              Compact, Ideal For High-Density CPO
            </span>
          </div>
          <div className="py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-medium text-[#d34c39] text-[14px]">
              Solid-State, Thermally Stable
            </span>
          </div>
          <div className="py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-medium text-[#d34c39] text-[14px]">
              Wafer-Level, Semiconductor-Compatible
            </span>
          </div>
          <div className="py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-medium text-[#d34c39] text-[14px]">
              Designed For High-Throughput Production
            </span>
          </div>

          {/* TRADITIONAL MICRO-OPTICS Section */}
          <div className="bg-[#EAEAEA] py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-medium text-[#676767] text-[14px] uppercase">
              Traditional Micro-optics
            </span>
          </div>
          <div className="py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-medium text-[#676767] text-[14px]">
              Thick, Curved, 3D Geometry
            </span>
          </div>
          <div className="py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-medium text-[#676767] text-[14px]">
              Wide, Diffuse Beam
            </span>
          </div>
          <div className="py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-medium text-[#676767] text-[14px]">
              Requires Active Mechanical Adjustment
            </span>
          </div>
          <div className="py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-medium text-[#676767] text-[14px]">
              Bulky, Limits Integration Density
            </span>
          </div>
          <div className="py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-medium text-[#676767] text-[14px]">
              Vulnerable To Deformation Under Heat
            </span>
          </div>
          <div className="py-4 px-4 border-b border-[#D3D0D0]">
            <span className="futura-medium text-[#676767] text-[14px]">
              Custom Fabrication, Complex Assembly
            </span>
          </div>
          <div className="py-4 px-4">
            <span className="futura-medium text-[#676767] text-[14px]">
              Difficult To Scale For High-Volume
            </span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default WhyCpo;
